// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG58wKB5MIgW2nsCSLK3SC7uG4WO95bak',
    appId: '1:436062103415:web:18314e777b697d7b78a372',
    messagingSenderId: '436062103415',
    projectId: 'prepwia',
    authDomain: 'prepwia.firebaseapp.com',
    storageBucket: 'prepwia.firebasestorage.app',
    measurementId: 'G-DWSYS4GYN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDLzYgOL1FSx9nbrkrExt3sKy7_O6DhZs',
    appId: '1:436062103415:android:0b140073a48026e978a372',
    messagingSenderId: '436062103415',
    projectId: 'prepwia',
    storageBucket: 'prepwia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQC40ajrDxCJ12HUO6Nb-kJ4XVZfTODCs',
    appId: '1:436062103415:ios:6ff9e6c916ceec7778a372',
    messagingSenderId: '436062103415',
    projectId: 'prepwia',
    storageBucket: 'prepwia.firebasestorage.app',
    iosBundleId: 'com.example.flutterBmiCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQC40ajrDxCJ12HUO6Nb-kJ4XVZfTODCs',
    appId: '1:436062103415:ios:6ff9e6c916ceec7778a372',
    messagingSenderId: '436062103415',
    projectId: 'prepwia',
    storageBucket: 'prepwia.firebasestorage.app',
    iosBundleId: 'com.example.flutterBmiCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG58wKB5MIgW2nsCSLK3SC7uG4WO95bak',
    appId: '1:436062103415:web:381de4e2dbd9e9b478a372',
    messagingSenderId: '436062103415',
    projectId: 'prepwia',
    authDomain: 'prepwia.firebaseapp.com',
    storageBucket: 'prepwia.firebasestorage.app',
    measurementId: 'G-CZZVQQD382',
  );

}